language: node_js
node_js:
- 6
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn test
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJX5YBBM7NONXHUZA
  region: us-east-1
  app: eng-box-rest-server
  env: eng-box-rest-server
  bucket_name: elasticbeanstalk-us-east-1-211533511749
  zip_file: server.zip
  bucket_path: eng-box-rest-server
  on:
    branch: hot-fix-for-cd
  secret_access_key:
    secure: Sf2y+wyqVQBHZggAS0Qe1+baLpVZjtQ3PG2997YQzMuV88DcTba614z+losmtktGYTUIoWxlRY5wg53gpYx/kBRQoeIIVh4AMepHM1HIx4hw0JoXId0AukYlGbsz0gxRw4+s0XdDyXF7rBqI3C3jacwsXf3aCw2VQlZ9lmMl5cNQwAgKo6TiW2oDtTTZqipvsKOJOHn+WpdVkL1JGyFFUmYf3NbtLE1weT4lUbVoZfyCCETVqJCHzkNTnMNh+Q7sllUC0sluGpg/J2ijvZt49gNvzq0O8zmt3yLPzVjnEGCwJ7QKEGsDkuVUFsr5rQIVIrVrpoElcmEmuzT3fo0dxuMd7Xpuo+l7iAym9BAf8QuLzCe4tc3Ic27SXY7l283uDPz5hzzyzHxud4n+8oAsIHdH6GMPlGI6DrvwXpTa045QFYXmi50oVSvxQPj70V45g5jfSNmT0yGQUsSAudP7+dOeLwkVfK2AArrc8uKDQjZlAQDUfoO8IKzEhe7HT/JtmTfTE8bakR6xFmK1nr+SU7VsvwNQttbxFL1Xmbd19xq+qkWiNnICMkoLH9eM3l1ykiE9aB/cs9uzuADK/B7M+d09wgXfWB7E6KwAhJLh7Ak4bKC59P7XxUoe2ck1s1c0fydRT/a6l/xm2n5kw7/3J92dq7oDFY+iwhWcCu17xOQ=
env:
  global:
    secure: dcsxt28h4aR/OlAiOAoO90XKz6wXdFGVD9DZBFZB5Gx+zdhMRUEcx1fU1Ev6EugG2oc5+kzgR5D2pNh3QtVJm1RWcnKvmCbw8uReYAB3MfqF4fkpDwN/GkMOoI+GtjPi/+3oqnYqbrrblc4ozQCO/8BPJIt8UmVCTVRcq8DZTEM6XNXCscHpZ9Abx3vBK4PzccKba6BZQKyLM5TELLMKxHHN3TY4+QQYcFSEU+vsSRlsLtQ4z9DKWwFoAeMGrXmRGOH5602u/58BJjvr8X/Aqa53+99wdpy1+rVw3zLA6czh4P5h3xXdj3I/19vfsWQzzRowAOjUGS5YHJ0slopj9+Zk5BLF7fUK9xpG1TzGqHfSx+BLGD24VEhf8WmAkagdLMsttYJwXGRB3Qj//XTx/wi9iDKUjFXO6uhlJ46ryjQqBMiEfQrYifBXXDdHBSKl67vnTuu6aYiXNv2aI0e5m7sFfZ+2UYpvWdQXl9W3JZbAuEjQJD+kmSOacnLnMVyHOWDwIRAy1WZEJcVY64YOSYRdFBthMk6OP6FbkatrpicOr0YQMbbGVlWMN2Y5X78sKHwo2v39fONqwkRlhX0DUhli/xC4wX4KGqG2F2l9Y3hrYciqlgFx7bbwCdozvARNWEViyDqlPxOEABo/XdZgZrsuak9yjrWFdb07d04cL2c=
before_install:
- openssl aes-256-cbc -K $encrypted_35dd3b90e6bd_key -iv $encrypted_35dd3b90e6bd_iv
  -in .env.enc -out .env -d
